[preface]
= Предисловие

== Мудрость толпы

В «Рассуждениях о первой декаде Тита Ливия» Никколо Макиавелли есть следующие строки:

____
«Что же до рассудительности и постоянства, то уверяю вас, что народ постояннее и много рассудительнее всякого государя. Не без причин голос народа сравнивается с гласом Божьим: в своих предсказаниях общественное мнение достигает таких поразительных результатов, что кажется, будто народ ясно предвидит».
____

В своей книге «Мудрость толпы» Джеймс Шуровьески писал: «при правильных условиях группы могут быть очень умными, а зачастую могут быть намного умнее, чем даже самый умный человек внутри группы». Он заметил, что коллективный разум обычно показывает лучшие результаты, чем небольшая группа экспертов, даже если члены группы не владеют всеми фактами или ведут себя иррационально, поступая по-своему.

Другими словами, группа случайных людей в среднем будет умнее нескольких экспертов. Этот тезис противоречит здравому смыслу и выглядит насмешкой над накопленной веками мудростью. Эксперты в области человеческого интеллекта (социологи, антропологи, психологи) встретили идеи Шуровьески далеко не с распростертыми объятиями. Он пошел дальше: «добавив в группу специалистов, вы сделаете ее глупее, а добавив дилетантов, повысите опять ее интеллектуальный уровень. Как и любой рецепт, это работает только при определенных обстоятельствах».

Я наткнулся на Шуровьески, когда стал работать над универсальным рецептом по построению сообществ. И сразу увидел, что его работа тесно перекликается с моими собственными наблюдениями, и что я могу устроить ей испытание. У меня была возможность не только применить, но и обкатать его идеи на многих сообществах и поискать им опровержение: все по-научному.

Это намерение дало начало процессу по построению умных, самоуправляемых, успешных онлайн-сообществ, которые раз за разом опережали экспертные группы. Эту дисциплину я назвал Социальной Архитектурой, что позволяло мне некоторое время называть себя «Социальным Архитектором» (сегодня я — пытающийся пробиться писатель, это звучит романтичней).

Социальная Архитектура по аналогии с привычной архитектурой является процессом и результатом планирования, разработки и становления онлайн-сообщества. Социальная архитектура в виде онлайн-сообществ — это культурные и политические символы и произведения искусства цифрового общества. 21 век будет ознаменован зарождением Социальных Архитекторов.

Успешные онлайн-сообщества обычно основаны на договоренности о взаимной выгоде, подразумеваемой или явной. Т.е. это возможность построить бизнес на миллиард долларов, основанный на добровольном труде участников, действующих из эгоистических побуждений. Часто участники не осознают или не придают значения тому, что они являются частью сообщества. Однако подоплека любого нашего действия — получение выгоды. «Краудсорсинг» является эксплуатацией добровольного труда для получения прибыли. И это работает только в том случае, когда толпа на самом деле хочет решить проблему, которую вы подбросили, или которую она обнаружила.

== Мудрее и постояннее всякого государя

Макиавелли не дал объяснений или подтверждений своему наблюдению. Однако понимание того, что коллективная воля является безошибочной и справедливой — vox populi, vox Dei — пронизывает современную культуру. Она поддерживает в нас веру в демократию и оправдывает наши требования прозрачности и доступа к информации. Это основа современной экономики, составляющие части которой — свобода выбора и торговли.

Шуровьески определил четыре элемента, необходимых для умной толпы: разнообразие мнений, независимость членов друг от друга, децентрализация и эффективные способы агрегировать мнения. Он описывает образцовую умную толпу как состоящую из многих независимо мыслящих и слабо связанных индивидуумов, которые географически и социально разнообразны, беспристрастны к предмету, обладают равным доступом ко многим источникам информации и имеют возможность объединить свои индивидуальные суждения в одно коллективное решение.

Согласно Шуровьески умные толпы выносят более точные и быстрые решения, самоорганизуются для лучшего использования ресурсов и сотрудничают без центральной власти. Некоторые примеры умных толп, такие как Википедия, чрезвычайно успешны, несмотря на интенсивную и непрекращающуюся критику со стороны негативистов и атак вандалов и конкурентов. Эти идеи настолько захватывающие, что остается только гадать, почему мы не наблюдаем все больше и больше умных толп. На самом деле, почему мир ширится глупостью, когда мудрость так возможна, так близка?

Есть много хороших объяснений для глупости многих толп, и я исследую детально этот вопрос в своей книге «Культура и Империя», откуда была взята эта часть. Мало кто пытался объяснить глупость толпы с точки зрения коллективного интеллекта. А без ясного понимания правильного действия, как мы можем надеяться объяснить неправильное?

Поэтому очевидная неудача коллективного разума убеждает многих в том, что это лишь забавная теория, которая не применима на практике. И все же если мы посмотрим на онлайн-сообщества, например на те, которые формируются вокруг популярного open-source проекта программного обеспечения вроде ZeroMQ, мы увидим группы, очень похожие на описанные толпы Шуровьески. И пока, может быть, сложно опознать умные толпы в реальной жизни, кажется, что они являются доминирующей моделью онлайн. Пробы и ошибки позволили цифровому обществу заново открыть принципы умной толпы и перенять их в качестве своих базовых принципов действия.

Решение цифрового общества древней проблемы коррумпированной власти элегантно и успешно. Существуют буквально миллионы сообществ, каждое из которых полагается на власть своих основателей. Граждане цифрового общества свободно выбирают, какие власти уважать и какие игнорировать. Основной фокус заключается в принятии власти без наделения ее «правом» командовать.

К тому же возникает острая конкуренция по созданию справедливой власти, которая бы не командовала, а принуждала соблюдать необходимые правила. Это взрывоопасная истина. Поколения, которые познакомятся с этой моделью, не согласятся — даже под угрозой смерти — уважать модель индустриального общества, где, при необходимости, для убеждения могут использоваться железные занавесы и вооруженные пограничники, где граждане буквально принадлежат Государству.

== Истоки Социальной Архитектуры

Я поставил кучу денег на Социальную Архитектуру и получил приличную выгоду. Она близка к строгим социальным научным дисциплинам, на стороне которых годы воспроизводимых экспериментов на реальных случаях и исследований существующих сообществ. В ней смешиваются психология, экономика, политология, технология, гуманизм и оптимизм во что-то такое, что, как я обнаружил, может сделать многих людей счастливыми.

Мое путешествие в область Социальной Архитектуры началось в конце 1990-х годов с изучения книги о том, как культы эксплуатируют наши социальные инстинкты. Секты — место не из приятных, конечно. Однако людей в них затягивает потому, что мы все — социальные животные, которые последний миллион лет ради выживания развивали инстинкт объединения и образования групп. Готовность уважать власть, подчиняться правилам, изучать общие языки и адаптироваться под общее поведение стало для нас второй натурой. Секты подвергают своих членов идеологической обработке, играя на этих инстинктах. Они разделяют членов с их семьями, исключают уединение, перегружают жаргоном, создают деспотичное правление, беспорядочно наказывают и награждают.

Подобным образом секты могут превратить большинство обычных людей в бездумных последователей, которые добровольно опустошат свои банковские счета, украдут у своих родных и будут работать годами, не требуя платы. Еще студентом, наблюдая исчезновения случайных друзей в подземельях Сайентологии и других культов, все это представлялось мне чем-то злокачественным и необъяснимым. Позже, когда мой ближайший кузен выпал из жизни и потратил пять лет своей жизни на Сайентологию, для меня эта тема стала личной.

Изучая материалы сайта Cult Information Centre (CIC), меня вдруг осенило, что все эти техники по промывке мозгов имеют несколько общих черт. Во-первых, они определенно нацелены на уничтожение того, что делает нас сильными — они атакуют независимое мышление и поведение. Во-вторых, они напоминают мне обстановку, в которой мне уже приходилось работать (крупный бизнес часто похож в своей деятельности на секту). В третьих, казалось, что все они реверсивные, т.е. их можно использовать в обратную сторону для благих дел.

Последнее наблюдение необычно. Если молоток разбивает окно, то вряд ли что-то изменится, если вы перевернете молоток. Но на некоторых примерах это наглядно видно. Вот одна из техник с сайта CIC: «Социальное давление в группе: подавляйте сомнение и сопротивление новым идеям, играя на потребности в принадлежности к группе». Реверс — снижение стоимости присоединения к группе и выхода из нее будет способствовать возникновению новых идей и критики». Или вот: «Исключение уединения — способность давать логическую оценку будет снижаться при отсутствии возможности размышлять наедине». Ее реверс: «предоставьте людям пространство и время для уединения, и они станут логичней размышлять».

Мои умозаключения — стойкие. Мы выживаем благодаря присоединению к группам, следованию за другими и попыткам понять мир. Некоторые группы существуют за счет одомашнивания нас и низведения до уровня животных. Другие — дарят нам свободу и позволяют стать сильнее, умнее и независимей.

В 2000 г. интернет еще не стал достаточно дешевым для масс, и open-source сообщества были маленькими, региональными, сосредоточенными вокруг университетов. Такие open-source сообщества как Debian Foundation до сих пор функционируют как классические некоммерческие организации, как легальные юридические лица с советом директоров, казначеями и пр.

В 2005 г. я стал участником ряда совместных проектов. С одной стороны, я был вовлечен в проект FFII, направленный на борьбу с патентами на программное обеспечение в Европе. Мы (хорошие парни) выступали в европейском парламенте, спорили с Европейским патентным офисом (плохие парни), организовывали семинары, предлагали поправки, собирали голоса и, вообще говоря, участвовали в сильнейшем лоббировании, которому когда-либо подвергался Брюссель.

С другой стороны, я занимался разработкой открытых стандартов, начиная с Advanced Message Queuing Protocol (AMQP). Культурный контраст между этими двумя организациями был очень сильным. FFII была группой безумных добровольцев, невероятно креативных, преисполненных холодной, жесткой решительностью остановить SAP, Siemens, Microsoft и Nokia (еще более плохие парни) в их стремлении изменить европейское законодательство с целью легализации серого рынка патентов на программное обеспечение. В рабочую группу AMQP входили банки и крупные компании-разработчики программного обеспечения, которые тоже оказались по-своему безумны, и при этом более неприглядны.

Оказавшись окруженным со всех сторон безумием, я вдруг опять подумал о важности исследований социальных инстинктов и сектантских техник. С моими друзьями из FFII мы запускали компанию за компанией. Сайты, петиции, рассылки по эл. почте, конференции… этому не было конца. Большинство из наших компаний не достигали достойного масштаба, лишь некоторые из них. Но что важнее, в течение трех лет мы экспериментировали и собирали информацию.

Мы поняли две важные вещи. Во-первых, культ является обратной стороной умной толпы. Сектантские паттерны казались отточенными, и я наблюдал, как одни люди применяют их по отношению к другим людям снова и снова. В любой тесной группе, семье, компании или команде начинают проявляться черты культа, в большей или меньшей степени. Все дело в градусе. Однако, как только вы тратите ваше свободное время на чей-то проект, вы существенно начинаете скользить вниз с этого склона. Я видел, как целые группы сходили с рельс и не могли больше думать трезво или выдавать точные результаты. Наблюдалась четкая причинно-следственная связь: чем больше группа становилась похожа на секту, тем более бесполезной она становилась.

Во-вторых, просто реверсировать сектантские техники не достаточно. Да, это помогает с самого начала развивать личную креативность и силу, но это не то же самое, что создание крепкого сообщества. Для этого вам требуются более конкретные паттерны. Определите убедительную миссию, чтобы привлечь новичков. Сделайте так, чтобы людям было легче начинать. Приветствуйте споры и конфликты, ведь в них рождаются хорошие идеи. Систематически делегируйте полномочия, создавайте соперничество. Работайте больше с добровольцами, чем с наемными сотрудниками. Добейтесь разнообразия и размаха. Пусть люди владеют работой, а не работа — людьми.

Конечно, намного дешевле и быстрее проводить крупные эксперименты с людьми онлайн, чем в реальном мире. Для подтверждения или опровержения рецепта по построению сообщества, все, что вам нужно сделать, так это создать пространство, определить некоторые правила игры, объявить об этом миру, откинуться на спинку кресла и ждать.

Мой самый крупный и наиболее успешный эксперимент на сегодня, к которому я буду часто обращаться — это сообщество программного обеспечения ZeroMQ. Оно выросло из команды, собиравшейся на одном из чердаков Словакии, в мировое сообщество, и оно используется тысячами организаций. Кроме того, ZeroMQ было полностью создано и руководилось своим сообществом: более ста создателей корневой библиотеки, и более ста связанных с этим проектов.
