Мой инструментарий социального архитектора состоит из 20 инструментов, каждый из которых соответствует какому-либо аспекту сообщества или группы. Их можно использовать двумя способами.

*Во-первых*, с их помощью вы можете делать *измерения существующего сообщества*, оценивая его по шкале от нуля и выше.

*Во-вторых*, вы можете использовать их для *создания сообщества*, при этом прилагая усилия там, где они наиболее необходимы.

* Четкая миссия – заявленная причина существования группы.
* Свободное участие – насколько легко люди могут присоединиться к группе.
* Прозрачность– насколько открыто и публично принимаются решения.
* Бесплатные участники – как много можно платить людям за участие.
* Свобода работы с материалами (ремиксабельность) – насколько свободно участники могут использовать работу друг друга.
* Четкость протокола – насколько хорошо прописаны правила.
* Компетентность власти – насколько хорошо следят за соблюдением правил.
* Нон-трайбализм – насколько далеко распространяются права группы над своими участниками.
* Самоорганизация – насколько свободно могут участники определять свои задачи.
* Толерантность – как группа разбирается с конфликтами.
* Измеримый успех – как хорошо группа может отслеживать свой прогресс.
* Высокое награждение – как группа вознаграждает своих участников.
* Децентрализация – насколько широко распределены участники группы.
* Свободная рабочая среда – насколько легко создавать новые проекты.
* Стандартная структура – насколько общая структура стабильна и предсказуема.
* Плавность обучения – насколько легко начать и продолжить учиться.
* Позитивность – насколько группа движима позитивными целями.
* Чувство юмора – насколько серьезно группа себя воспринимает.
* Минимализм – сколько лишней работы делает группа.
* Разумное финансирование – как группа борется за выживание в экономическом плане.

Спасибо Сергею Даньшину за помощь с переводом.

Мы рассмотрим эти инструменты поочередно и увидим, как они работают в разных сообществах. Для начала несколько общих советов о создании сообщества. Будьте предельно честны с собой и с другими. Главное для вас – это преодолеть собственные предубеждения и пристрастия, а уже потом – те, что присущи вашим коллегам.

Каким бы инструментом я вас ни снабдил, вы захотите адаптировать его и подогнать к собственным нуждам. Социальная архитектура является все еще молодой наукой, и многие из моих инструментов будут слишком громоздкими или неполными.

Вот лучший способ, как поступить:

* Пользуйтесь вашим собственным продуктом.
 Если вы не будете фанатичным пользователем продукции вашей группы, считайте себя полуслепым. Я осознал это, когда работал в компании-производителе пива Nigerian Breweries в 1990-х годах: наслаждаясь пивом, я научился оценивать бизнес по продаже пива намного глубже.
* Практикуйтесь и повторяйте пройденное.
 Экспериментировать дешево, а неудачи неизбежны. На самом деле, если вы начнете проект, а он не удастся, то никто и не заметит. Поэтому начинайте много проектов и меняйте или отлаживайте ваши инструменты, если они не работают. Займитесь оперативной поддержкой пользователей. Во всех сообществах есть места, куда обращаются новички, чтобы задать вопрос. Будьте там, наблюдайте, почему новопришедшие теряются, какие делают ошибки, и на основе этого вносите соответствующие правки в вашу разработку. Возможно, они заблуждаются насчет основного предназначения. Или, может, им непонятна структура. Хороший разработчик симпатизирует своим пользователям, сопереживает и помогает им.
* Выпускайте релиз сразу и почаще.
 Это мантра разработчиков свободного ПО. Это очень правильно. Вы хотите вести разработку в открытую и получать критические отзывы, и чем раньше, тем лучше. Мы в ZeroMQ выпускали патчи, как только они были готовы.
* Учитесь и преподавайте постоянно.
 Обучение других позволяет видеть перспективу, а изучение нового самому позволит в дальнейшем использовать новые инструменты. Социальная архитектура – молодая дисциплина, и хотя ее корни уходят вглубь человеческой психологии, перед ней еще стоит много вопросов.

=== Четкая миссия

Отправная точка создания любого сообщества – формулировка его миссии. Она определяет цели, которые мы разделяем, еще до того, как присоединиться к проекту. Это как заголовок сайта или рекламный лозунг фильма. Например, заголовок у Reddit звучит так: «главная страница интернета» – амбициозная миссия, которая, тем не менее, выполнена. Слоган Фейсбука: «помогает вам связаться и поделиться с людьми в вашей жизни».

*СОВЕТ:* используйте вашу миссию в качестве слогана на сайте, в рекламе, в презентациях и т.д. Если вы инвестируете деньги в ваше сообщество, подумайте о том, чтобы зарегистрировать формулировку миссии как торговую марку.

Без четкой миссии онлайн-сообщество не будет расти. Друзья, которые начали заниматься проектом, могут быть все согласны с тем, чего они хотят достичь, но каждому новичку придется гадать, что они имеют в виду. Люди будут заблуждаться в своих догадках и со временем могут изменить свое мнение. Будут возникать разногласия, путаница и разочарование по мере понимания людьми того, что их тяжелый труд был впустую, т.к. остальная часть группы движется в другом направлении.

Реакция людей на миссию компании не должна быть «да, это благоразумно», а наоборот: «вы же это не серьезно, так?!». Миссия Википедии – https://en.wikipedia.org/wiki/Main_Page["«бесплатная энциклопедия, которую любой может редактировать»"], – хороший тому пример. Это было изначальной целью, поэтому все прочие, кроме считанных идеалистов, отнеслись к этому как к чему-то невозможному и бредовому. На это и был расчет Википедии: чтобы эти идеалисты однажды взошли на борт. Невозможные цели привлекают правильных людей к молодому проекту.

*СОВЕТ:* Меняйте миссию по мере взросления вашего сообщества. Вначале вы захотите привлечь молодых идеалистов и первопроходцев, потом – лидеров, а потом – первых адептов, широкую общественность, дальнейших последователей. Каждая из этих групп стремится к разному. Поняв это, соответственно измените миссию.

Чтобы сформулировать хорошую миссию, ориентируйтесь на одну основную проблему, которой посвящен ваш проект. Reddit, например, решает проблему того, как получить новости из интернета при слишком большом количестве ресурсов с интересной информацией. Его «основная страница» представляет собой цифровую газету 21-го века. Википедия решает проблему аккумулирования знаний миллионом умов. Слова «любой может редактировать» – так же, как и «Глас народа – глас Божий», – говорят о том, что если и возможно найти истину, то только сообща.

*СОВЕТ:* При намерении сделать что-либо, много или мало, всегда старайтесь начать с определения проблемы, которую вы хотите устранить. Только когда у вас будет четкая и реальная проблема, с наличием которой все согласны, только тогда приступайте к обсуждению возможных ее решений. Решение вымышленной проблемы схоже с группой без четкой миссии. У вас может быть несколько миссий, случайно или преднамеренно. Если миссии тянут сообщество в разных направлениях, это может кончиться плохо. Например, рост группы может потребовать вложений, что вступит в противоречие с позицией по вопросу прибыли. Если бы Википедия стала коммерческой организацией, с рекламой и комплектом высокооплачиваемых менеджеров, то это, по-вашему, привело бы к ее расширению или упадку?

В случае с ZeroMQ наша миссия звучала так: «Быстрейшая. Передача сообщений. Всегда». Это хорошее и почти невозможное решение проблемы, насчет существования которой мы все соглашались, а именно: доступные на тот момент технологии были медленными и неповоротливыми. В то же время, мы с моим партнером-основателем Мартином расходились в целях. Он хотел создать лучший из возможных программных продуктов, я же хотел создать крупнейшее из возможных сообществ. По мере того, как росло число пользователей, его драматическое изменение, что сломало существующие приложения, причинило усиливающуюся боль.

В данном случае мы смогли сделать всех счастливыми (Мартин ушел, чтобы работать над созданием новой библиотеки, названной «Nano»). Тем не менее, если вы не можете разрешить противоречия, касающиеся миссии, они могут серьезно навредить проекту. Проекты могут вынести многие споры, а вот разногласия между основателями довольно травмоопасны.

*СОВЕТ:* Если основатели согласны, что «успех» определяется как «максимально возможное сло участников», то в последующие годы это может помочь в сохранении целеустремленности. Это также облегчает измерение вашего успеха по мере развития.

=== Свободное участие

Определившись с миссией, вам нужно протестировать ее в реальном мире. Это значит, вам нужно дать краткий, но убедительный ответ на ту проблему, на которую вы нацелились. Я называю это «посевом». Этот процесс преследует две основные цели. Во-первых, начать собирать идеалистов и первопроходцев (в основном тех, кто был настолько безумен, чтобы поверить вам) в сообщество. Во-вторых, доказать или опровергнуть вашу миссию.

Проекты могут кончиться неудачей по многим причинам. Но главная причина — основополагающая идея или миссия были не настолько удивительными, как того ожидали люди. Неудача – нормально, даже отлично, если только она не стоила нескольких лет вашей жизни. Посадить семечко и показать его только нескольким людям не достаточно, потому что большинство людей не будет критиковать. Из жалости. Однако попросите их потратить хотя бы несколько часов своего времени на то, чтобы сделать проект лучше, и если они не скажут «да», тогда вы поймете их настоящее отношение.

*СОВЕТ:* Привлеките к «посевному» проекту внимание публики и вдохновляйте людей присоединяться к нему с самого начала. Если люди вовлекаются в проект, скорее их продвигайте. А если этого не происходит, то считайте это знаком того, что ваша миссия может быть ложной. Используйте «посевной» проект, чтобы создать сообщество.

Когда люди соглашаются помогать вам, нужно обеспечить им место для совместной работы. Вам нужна «платформа для сотрудничества». Две моих самых любимых: http://wikidot.com/[Wikidot] для информационных сообществ и http://github.com/[GitHub] для проектов по разработке ПО. Платформа должна быть бесплатной. С ней должно быть легко и в учебе и в работе. Ваш посевной проект должен быть виден анонимным участникам. Он должен работать для кого угодно, вне зависимости от его или ее возраста, пола, образования или местоположения.

Все это позволяет потенциальным заинтересовавшимся незнакомцам зайти и посмотреть на вашу работу, и если им она приглянется и они почувствуют в ней вызов, то смогут постепенно вовлекаться в проект. Вы хотите работать над вашим посевным проектом публично и говорить о вашем новом проекте с самого начала. Это значит, что люди смогут делать предложения и чувствовать вовлеченность с самого первого дня.

Если мы как основатели группы выбираем тех, с кем будем работать, мы создаем основание для предвзятого выбора. Намного легче работать с теми милыми, умными людьми, которые соглашаются с нами, чем с теми идиотами и критиками, которые выражают свое несогласие. А когда вы соглашаетесь со мной, вы подтверждаете все те мои иллюзии и допущения, которые, как я знаю по собственному опыту, могут оказаться ложными самым удивительным способом.

Со временем увеличение количества людей, которые разделяют те же неверные допущения и предубеждения, может привести к гибели проекта. Например, при разработке программных протоколов требования к крупным компаниями могут сильно отличаться от требований к маленьким open source командам. Поэтому если комитет по протоколу состоит полностью из крупных компаний, то результат их деятельности будет неприемлем для массового рынка.

Решением является свободный доступ для всех заинтересованных, какой бы безумной и непохожей ни была бы их точка зрения. Это дает нам в перспективе широкое и разностороннее сообщество – предшественник умной толпы. В ZeroMQ мы никогда не отворачивались от тех, кто хотел участвовать. Я втягиваю людей, даже если их вклад в общее дело мал или неверен. Сообщество важнее, чем продукт.

Когда сообщество посевного продукта созреет, участники захотят создать его второе поколение. Как социальный архитектор, вы должны руководить этим так, чтобы усилия умной толпы были направлены на разработку «реального» продукта. Возможно, где-то на этом этапе вы захотите найти хорошее доменное имя и сделать «приличный» веб-сайт.

*СОВЕТ:* Если люди не присоединяются к вашему посевному проекту, не продолжайте заниматься им. Вместо этого разберитесь, что их останавливает, и устраните это. Начните заново с прополки. Не убивайте преждевременно побеги, людям требуется время, чтобы оценить то, что вы пытаетесь сделать.

=== Прозрачность

Прозрачность очень важна для быстрого получения критики идей и прогресса в работе. Если несколько людей из команды отчаливают и работают над чем-нибудь вместе некоторое время, например пару дней, ничего страшного, но вот когда речь идет о неделях, тогда то, чем они занимаются, следует представить группе как свершившийся факт. Если один человек так поступает, то группа может просто отмахнуться от него. Но если двое или больше – становится сложным откреститься от плохих идей. Секретность и некомпетентность идут рука об руку. Группам, работающим втайне, не постигнуть мудрости.

*СОВЕТ:* Когда один человек делает что-то в темном углу – это эксперимент. Когда двое или больше делают что-то в темном углу – это тайный заговор.

В случае с ZeroMQ ушло несколько лет на то, чтобы создать по-настоящему открытую и прозрачную атмосферу. До этого главные участники работали тайно, публикуя свою работу только тогда, когда считали, что она готова к общественному обозрению. Но когда они это делали, остальному сообществу было сложно сказать «нет». И зачастую работа была не в тему… да, отличным решением проблемы, но до которой никому нет дела. В конце концов, мы недвусмысленно запретили подобные вещи.

Иронично, что тайна кажется неотъемлемой в некоторых бизнес-моделях. Прибыль часто приходит от игнорирования потребителей. Большинство коммерческих предприятий, даже такие большие сообщества, как Twitter, зависят от строгого разграничения «их» и «нас». Однако цифровое общество лучше всего растет, когда масштаб приоритетней прибылей и когда относится к пренебрежению как к проблеме, требующей решения. Если ваши клиенты не допускаются до ваших внутренних процессов, то вам будет закрыт доступ к пониманию, где в них кроются ошибки.

=== Бесплатные участники

Деньги – забавная вещь. Слишком мало – и сообщество будет умирать с голоду (я вернусь к этому позже). Слишком много – начнется разложение. Необходимо понимать, почему каждый из участников вообще занимается этим. Какие у них экономические мотивы? Даже в добровольных сообществах каждый участник преследует свои интересы.

Мы в ZeroMQ изначально начали с малооплачиваемой группы и через два года пришли к добровольному сообществу, прагматично – если не сказать циничнее – умышленно потратив деньги и оказавшись вынужденными уволить разработчиков. Некоторые из них растворились в других компаниях, некоторые вернулись в качестве участников, и проект стал более захватывающим и веселым, чем был раньше. Люди работали над ZeroMQ, потому что им это было нужно для собственных проектов – потратив немного времени на его улучшение, они выигрывали или экономили в разы больше.

Когда вы работаете на кого-то, то будете делать то, что он или она хочет. Когда вы работаете на себя, вы делаете то, что нужно вам. Это огромная разница. Люди с деньгами, но без навыков или вкуса, – шелуха общества. Мы презираем оплачиваемых участников Википедии, платных блогеров и модераторов на Reddit, потому что мы знаем, что выражаемые ими мнения почти по определению ложь. Будет ли блогер, проплаченный Голливудом, критиковать новый летний блокбастер?

Я не имею ничего против наемных сотрудников. Однако если вы нацелены на создание наиболее крупного, наиболее успешного сообщества, то вам нужны участники, который будут стараться по честным, понятным причинам. Если кинорежиссёр приходит на Reddit обсудить фильм – здорово. Если его маркетологи заходят, чтобы потереть критические комментарии, это отвратительно.

*СОВЕТ:* один бесплатный участник стоит десяти оплачиваемых сотрудников.

=== Свобода работы с материалами (ремиксабельность)

Группе требуется много договоренностей, чтобы работать сообща. Я называю их «протоколами». Наверно, самый важный из них для творческого сообщества – возможность перерабатывать материал (ремиксабельность). Будь то музыка, искусство, изображения, видео, комментарии, программы или wiki-страницы, встанет следующий вопрос: «А что за авторская лицензия стоит за этим материалом, и как это затронет сообщество?».

Грубо говоря, есть три типа авторских лицензий:

* А) лицензия locked down не позволяет перерабатывать материал. Это старый способ вести дела, и он все еще доминирует в коммерческой деятельности.
* Б) лицензия free to take позволяет одностороннюю переработку. Это доминирующая модель для многих open source сообществ.
* В) лицензия share-alike позволяет двустороннюю переработку. Это преобладающая модель для сообществ бесплатного программного обеспечения, таких как ZeroMQ, и для многих художественных сообществ (хотя это может быть и неписаной договоренностью).

Пользователи предпочитают модель free to take, потому что она позволяет им использовать контент как угодно без обратных обязательств. Представьте себе диджея, который выпускает популярный трек по модели free to take. Потом компания делает ремикс и использует его в рекламе. И этот ремикс будет закрыт для использования. Теперь, диджей не сможет переработать этот ремикс и, возможно, не сможет даже проигрывать этот ремикс.

Все же сообщества работают лучше с третьей моделью, т.к. тогда пользователи становятся участниками. С лицензией share-alike диджей смог бы использовать ремикс, ремикшировать его еще и превратить в дискотечный хит. Знания и идеи текут во всех направлениях, а не вытекают из сообщества в застойное болото. Это мощное течение, и это особенно важно для тех из нас, кто строит сообщества с минимальным бюджетом. Если вы являетесь крупной компанией, вкладывающей кучу денег в сообщество, то модель free to take вам подойдет лучше.

*СОВЕТ:* Если каждый участник владеет тем, что он привнес в сообщество, а вы используете лицензию share-alike, вам не требуются переуступки авторских прав или возобновление лицензии от участников.

=== Четкость протокола

Хорошие протоколы позволяют посетителям участвовать без предварительного одобрения. Они разрешают деструктивные конфликты и превращают их в полезные состязания. То, что анархисты могут присоединяться к умной толпе так же успешно, как и любой другой, объясняется тем, что толпа может разрабатывать свои собственные правила. Обычно эти правила касаются переработки материала, идентичности, рангов и т.д. Не важно, какая у них форма, хорошие правила просты, четки, ясно прописаны и всеми одобрены.

Если вы создаете проект в области программного обеспечения, вы можете взять существующее руководство, например, http://rfc.zeromq.org/spec:2[протокол С4], который мы сделали для ZeroMQ. Или же вы можете начать с минимумом инструкций и добавлять их по мере определения тех проблем, с которыми сталкивается сообщество. К слову, так было и с http://simple.wikipedia.org/wiki/Wikipedia:Rules[руководством Википедии]. Некоторые правила должны быть установлены с самого начала (например, об авторских правах и участии). Другие могут быть придуманы по мере необходимости (например, процедура разрешения конфликтов). Сложные, бесцельные или не прописанные правила отравляют группу. Они создают пространство для споров, путают людей и повышают стоимость входа в группу или выхода из нее.

*СОВЕТ:* Пишите аккуратно ваши правила, начиная с лицензии на контент, и оценивайте, насколько они помогают людям. Изменяйте их по мере необходимости.

=== Компетентность власти

Без органов власти правила не имеют силы. Основатели сообщества и основные участники являются де-факто их представителями. Если они злоупотребляют своим положением, они теряют участников – и проект умирает либо разветвляется в зависимости от различных правил. Власть должна быть масштабируемая (то есть быть способной охватывать деятельность группы любого размера) и допускать передачу по мере роста и изменения группы.

Пока мы используем власть для сооружения игровой площадки, многие группы используют власть для контроля своих членов, держа их в группе и заставляя их соответствовать стандартам. Любимый прием в культах – наугад наказывать и вознаграждать людей, чтобы они были сбиты с толку и перестали задавать вопросы администрации.

*СОВЕТ:* Назначайте самых активных участников на административные посты и побыстрее. У вас есть небольшой промежуток времени, чтобы успеть сделать это, иначе они уйдут в другие проекты.

Вы должны быть частью вашего сообщества, и вы должны соблюдать ваши собственные правила. Если вы замечаете за собой, что нарушаете их или хотите это сделать, значит, они неточны и требуют корректив.

В сообществе ZeroMQ мы сражались из-за вопроса о том, кто мог определять правила, и в конце это привело к торговой марке и доменному имени. Человек или компания, которая владеет именем проекта, является верховной властью и может определять правила. Если они идиоты, то проект умрет.

*СОВЕТ:* Если вы инвестируете деньги в сообщество, рассмотрите вариант использования торговой марки в США, чтобы иметь возможность предотвращать использование другими людьми похожих имитирующих названий, которые не имеют к вам отношения. Это стоит около 750 долларов.

=== Нон-трайбализм

Членство должно быть символом объединения, а не служить удостоверением. Как часто отмечал Мистер Спок, эмоции не логичны. Некоторые группы руководствуются логически обоснованными целями, в других же правят эмоциональные факторы, такие как давление со стороны членов своего круга, стадный инстинкт и даже коллективная истерия. Определяющим моментом, видимо, служат отношения между группой и ее участниками. Мы может выявить это вопросом: участники «исключительно привержены» группе? Под исключительной приверженностью имеется в виду придание большего значения существованию группы, а не ее работе. Подобная приверженность заканчивается конфликтом с другими группами.

*СОВЕТ:* Держитесь подальше от формальных моделей членства, особенно тех, которые стараются превратить людей в собственность группы. Позволяйте анонимное или не персонализированное участие. Поощряйте людей создавать свои конкурирующие проекты – пространство для экспериментов и для изучения нового.

Группы индустриальной эпохи, словно культы, владеют своими членами. Сотрудник принадлежит компании. Даже идеи, которые пришли вам в голову под душем, – тоже собственность вашего работодателя. А когда группа владеет своими участниками, то мотивирует их страхом, ненавистью, завистью и злостью, подменяя сознательные логичные мотивы. Страх исключения широко используется для подчинения людей одному стандарту: «Делай, что я говорю, или я уволю тебя!».

*СОВЕТ:* Для определения того, насколько группа похожа на племя, просто начните конкурирующий проект. Если реакция на это отрицательная и эмоциональная, в группе доминирует родоплеменная парадигма. В группе со здоровой атмосферой аплодисментами встретят своих соперников.

=== Самоорганизация

Некоторым людям нравится, когда им говорят, что делать. Лучшие участники и команды сами выбирают себе задачи. Успешное общество распознает проблемы и само организуется для их решения. Более того, оно делает это быстрее и лучше, чем любая иерархически управляемая структура. Это значит, что сообщество должно принимать помощь в любой области, без ограничений.

Распределение задач сверху вниз является антипаттерном с присущими ему многими слабостями. Он не дает индивидуумам действовать при обнаружении ими проблемы. Для него характерны феоды, где работа и необходимые ресурсы принадлежат отдельным людям. Он создает длинные коммуникационные цепочки, которые не позволяют реагировать быстро. Ему требуются прослойки менеджеров, просто чтобы соединить тех, кто принимает решения, с теми, кто будет выполнять работу.

*СОВЕТ:* Пишите правила, чтобы повысить качество работы, подчеркивающие, что каждый может работать над тем, что ему интересно.

В сообществе ZeroMQ мы избавились от назначения задач. Например, мы не принимали запросы о каких-либо особенных функциях. Если кому-то нужна была специальная функция, то он либо посылает нам патч, либо предлагает оплатить добавление изменений, либо он ждет. Это значит, что люди делают только те изменения, которые на самом деле нужно сделать.

*СОВЕТ:* Сообществам требуется иерархия полномочий. Однако она должна быть подвижной и строго делегированной. То есть выбирайте людей, с которыми вы работаете, и позвольте им выбирать тех, с кем они будут работать. Структура полномочий, словно жидкий цемент, она затвердевает и сковывает движения людей. Любая структура старается себя защитить.

=== Толерантность

В разношерстной группе возникают конфликтующие мнения, и здоровая группа эти конфликты охватывает и перерабатывает. Критики, иконоборцы, вандалы, шпионы и тролли держат группу в напряжении. Они могут быть катализатором вовлеченности остальных участников. Википедия процветает благодаря, а не вопреки, тем, кто кликает «Edit» с целью превратить статью в мешанину. Это классический антипаттерн, подавляющий идеи и взгляды меньшинства, используя предпосылку, что они «опасны». К тому же это неизбежно подавляет новые идеи. Логика обычно в том, что слаженность группы важнее ее разнообразия. Потом же получается так, что на ошибки не реагируют, а лишь еще больше обособляются. На самом деле, группа может быть важнее, чем результаты ее деятельности, если она многообразна и открыта новым аргументам. Это трудный урок, который полезен и обществу в целом: нет опасных суждений, есть опасные ответы.

То, как сообщества разбираются с троллями и вандалами, это одно. Разобраться с фундаментальными отличиями мнений – это другое. Ранее я говорил, что конфликтующие друг с другом миссии могут стать проблемой. Лучшее решение, которое я знаю, – это превратить конфликт в состязание. К примеру, браузер Google Chrome стал более легкой, более быстрой альтернативой Firefox, который становился раздутым и медленным. Тогда команда Firefox взялась за дело с умом, и теперь Firefox работает быстрее, чем Chrome.

*СОВЕТ:* Если есть интересная проблема, сделайте так, чтобы несколько команд соревновались, пытаясь решить ее. Соревнование — очень веселая штука, и может породить лучшие решения, чем монополистический подход. Вы можете даже организовывать соревнования с призами.

=== Измеримый успех

Все это хорошо: пытаться обратить конфликт в состязание. Однако вам необходимо обеспечить участников группы информацией о том, как хорошо они справляются. Лучшие инструменты, такие как GitHub, показывают точное число людей, которые наблюдают или отметили проект или начали проект-ответвление (отражены различные уровни интереса и приверженности).

Конечно же, Сеть всегда была озабочена «хитами» и анализом траффика, который показывает популярность сайта или страницы. Это облегчает измерение успеха онлайн-проекта. В старые времена индустриальной эпохи команды получали отзывы о своей работе от начальства. Что превращалось в ужимки перед властью: вас больше наградят за послушность, чем за прилежность. Делать начальство счастливым ради того, чтобы вам повысили зарплату, – не здоровое отношение.

*СОВЕТ:* Если ваша платформа не поддерживает этого напрямую, найдите возможности информировать ваших участников о том, насколько хорошо развиваются их проекты.

=== Высокое награждение

Существует много причин, по которым люди принимают участие в сообществах. Преобладающая мотивация – потребность в восхищении за достигнутый успех. Как индивидуумом, так и в составе команды. Успех относительное явление, поэтому нам требуется метрика, какой-то высокий балл, на который люди будут ориентироваться в своих стремлениях.

В сообществе ZeroMQ мы не придавали большого значения балльной оценке, хотя участники и получают больше любви при большем вкладе в общее дело. Это записывается в их послужной список. Участие в ZeroMQ может помочь при поиске хорошей работы.

Reddit, как многие другие сайты, использует «карму», которая показывает, сколько голосов получил аккаунт за свои публикации и поведение. Работает это довольно неплохо. Некоторые сайты не показывают всю карму, чтобы предотвратить попытки людей обойти систему и получить более высокий балл. Некоторые сайты, такие как StackOverflow, до крайности увлекаются «геймификацией», используя ордена, высокие баллы, достижения и т.д. Мне кажется, это отдает манипуляциями и отвлекает от миссии сообщества. Люди должны принимать участие, стремясь к успеху проекта, а не к большому количеству игровых баллов.

Социальное обязательство – делать группы разных людей счастливыми – задача, приносящая огромное удовлетворение, и она не загрязняет планету. Индустриальное общество нацелено на материальные награды (выше зарплата, больше дом, лучше машина), увязанные с иерархической структурой. Оно эффективно, потому что все мы любим богатство или у нас комплекс неполноценности; какая бы ни была причина, желание сделать начальство счастливей значит принятие меньших рисков.

*СОВЕТ:* Когда люди просят вас сделать что-то, а вы не знаете как, тогда объявите публично, что это «невозможно». Или предложите решение настолько нелепое и безнадежное, что настоящие эксперты от возмущения возьмутся за дело.

=== Децентрализация

В своей книге Сероуиеки (Surowiecki) объясняет, что катастрофа шаттла «Колумбия» произошла по причине бюрократии в иерархичной структуре управления NASA, из-за которой были проигнорированы мнения обычных инженеров. Если группа децентрализована, ее члены более независимы, они получают большее различных входных данных, и они с самого начала разнообразны.

Если группа географически не разбросана, то она становится однородной, где все члены обладают схожими входными данными и триггерами. Схожесть позволяет меньшинству доминировать над настроем группы и отбрасывать неординарные идеи. Оно позволяет ему буквально запугивать или обманывать большинство, тем самым подчиняя его. Требование о том, чтобы все члены группы сидели в одном офисе, департаменте или здании является старым антипаттерном, который сложно преодолеть. Вот почему все культы такие сплоченные.

*СОВЕТ:* Вам нужны собрания, чтобы добиться от группы работы? Это знак того, что у вас есть глубокие проблемы в совместной работе. Вы исключаете людей, которые физически не находятся рядом.

Бывает сложно отойти от старой модели совместной работы «обсуждение-действие». И, конечно, вам будет легче, если вы собираете группы с самого начала, а не пытаетесь изменить уже существующие.

=== Свободная рабочая среда

Сообществу нужно пространство для роста. В реалиях интернета это обычно сайт или набор сайтов и сопутствующие структуры вроде списков эл. почты, блогов и т.д. Мы видим, что это становится очень дешевым или даже бесплатным способом создания «пространства» в цифровом обществе. Вопрос в том, могут ли индивидуумы создавать свои личные пространства внутри сообщества. Если да, будут ли они приносить больше пользы общему проекту?

Свобода создания структуры раздражает людей, которые считают, что это вносит хаос и беспорядок. Однако если вы используете обычные структуры (смотрите следующий пункт), ущербу участникам от этого нет никакого. А вот что вредно, так это создание структуры исходя из необоснованного мнения о ее пользе людям. Когда я возглавил ассоциацию FFII в 2005 г., предыдущим президентом было создано несколько сотен списков эл. почты, так он отмечал те проекты, над которыми, по его мнению, люди должны были работать. Это не соответствовало тому, как люди хотели быть организованы, и было очень сложно удалить эти списки и создать новые, которые нам на самом деле были нужны.

Конечно, группы индустриальной эпохи распределяли работу и ресурсы для ее выполнения. Любая новая инфраструктура – такая как сайт, список адресов эл. почты или вики – требует одобрения и решительности. Может даже потребоваться юридическая оценка авторских прав и патентов. Цена высока, поэтому люди неохотно идут на риск. Получается, что не экспериментируя и продолжая работать, они связывают себе руки.

В сообществе ZeroMQ требуется лишь один клик для создания нового проекта. В Википедии вы можете создать новую страницу, просто кликнув на «создать страницу». Оба проекта имеют механизмы защиты от случайного мусора. Википедия проводит довольно агрессивную чистку новых страниц. В ZeroMQ есть специальная процедура для внесения проекта в официальную организацию сообщества.

*СОВЕТ:* Сделайте создание новых проектов для зарегистрированных пользователей максимально простым. Если проект создается пользователем, то не стоит беспокоиться насчет мусора. Если они находятся в общем пространстве, то вам могут потребоваться инструменты для очистки мусора и заброшенных проектов.

=== Стандартная структура

По мере того как сообщество растет, направлять его становится сложнее. Если вы делаете единичный, постоянно развивающийся проект, состоящий из множества отдельных задач, то это становится все сложнее и сложнее со временем. Представьте себе средневековый замок. Эта проблема особенно остро стоит перед большими компаниями, развивающими проект, которые иногда забывают о затраченных средствах.

Запутанность отпугивает людей – очень сложно становится разобраться. Решением является использование стандартных структур, выучив которые раз, вы можете распознавать всегда. Подойдет не любая структура. Нам бывает сложно выучить структуры глубже трех-четырех уровней. Однако мы с радостью исследуем очень широкие системы с тысячами или миллионами блоков, если эти блоки соответствуют отдельным задачам или проектам.

Представьте себе город.

Успешные онлайн-сообщества – это города, а не замки. Википедия состоит из нескольких вики со специфичным языком, многие разбиты на миллионы страниц (проектов), каждая структурирована секциями, обсуждением, историей, примечаниями и т.д. Несколько людей могут работать над одной страницей одновременно или один человек может медленно править или заботиться о дюжине или сотне страниц.

GitHub управляет миллионами программных хранилищ («репозиториями»), сгруппированными по учетным записям пользователей или организаций, и каждый обладает своей структурой (файлы-исходники, документация и т.д.), что зачастую зависит от языка (Java-репозитории используют один стиль, С-репозитории – другой и т.д.). Один репозиторий может насчитывать несколько участников, люди могут работать с разным количеством репозиториев. Сообщество ZeroMQ является организацией, которая состоит из растущего числа проектов.

*СОВЕТ:* Спроектируйте ваше сообщество как город поддающихся поиску проектов, где любой может начать новый проект – проекты представляют, наверно, дюжину работ людей, и у всех схожая структура, насколько это возможно. Бизнес тяготеет к замкам, которые неизбежно будут посвящены Важным Персонам, а не проектам, и, конечно же, не основным проблемам бизнеса. Эти организации всегда огромны и нестандартны. И нет никакой возможности разобраться в них, кроме как запоминать каждую их деталь. Но и тогда вы не сможете с легкостью прогуливаться по замку, поэтому мало толку изучать его планировку.

=== Плавность обучения

Когда ZeroMQ только начинался, это был лишь один проект с единственной страницей README. Сегодня это сто или больше небольших проектов, каждый из которых имеет свою документацию, сообщество и динамику. Попасть в уже взрослый проект может быть трудно. Как я уже сказал, использование стандартных структур жизненно необходимо. Более того, вам потребуется проследовать по довольно специфической траектории при изучении, от легкого к более сложному, от стадии праздного посетителя до участника-эксперта. Считайте ваше сообщество компьютерной игрой, где сложность уровней возрастает соразмерно с выигрышем. Люди будут играть «в соответствии со своим уровнем». Если вы все делаете правильно, вы привлечете многих. Если неправильно, то эксперты будут скучать на легком уровне, а новичков отпугнет сложность на старте.

*СОВЕТ:* Используйте классические инструменты обучения – презентации, видео, ответы на часто задаваемые вопросы (FAQ), обучающие материалы – чтобы люди могли начать. Вам будет легче, если вы состоите в сообществе, потому что тогда вы можете посмотреть, какие вопросы чаще всего задают начинающие.

=== Позитивность

Иногда есть соблазн агрессивно агитировать людей вступить в сообщество. В конце концов, многим нравятся острые аргументы, особенно когда они уверены в своей правоте. Некоторые группы развиваются за счет своей враждебности и негатива по отношению к другим группам, особенно если еще есть и предыстория. Тон, который вы задаете, будучи основателем, сохранится на долгое время. Если вы продвигаете свое сообщество, нападая на конкурентов, вы привлечете определенно настроенных людей, и такой настрой получит развитие. Рано или поздно негатив обернется внутрь и может оказаться губителен для сообщества.

*СОВЕТ:* Когда вы говорите о людях, продукции или организациях, будьте вежливы и не теряйте самоконтроль. Когда вы рекламируете продукцию или сообщество, говорите о проблемах, которые вы решили, а не о том, чем вы лучше конкурентов.

На своем опыте знаю, что лучше задать позитивный тон с самого начала. Конкуренты – это благо, т.к. дают на возможность состязаться. Подражатели – тоже хорошо, потому что подтверждают, что рынку вы нужны. Тролли и вандалы – отлично, ведь они дают искренним людям дополнительный шанс доказать свою полезность. И так далее. Кажется, что это трудно, искать позитивную сторону во всем. Однако это всего лишь образ мышления.

*СОВЕТ:* Добро пожаловать всем, за исключением безнадежных смутьянов. Их немного, тех, которые просто не могут найти себе место в открытом, разнообразном сообществе. Вы можете попросить таких людей уйти, или, если необходимо, забанить их.

Позитивный настрой характеризуется толерантностью и препятствует накалу страстей и возникновению споров. Так легче экспериментировать, делать ошибки и критически относиться к своей работе, а все это вместе взятое позволяет сообществу решать сложные задачи.

=== Чувство юмора

Вы когда-нибудь задумывались, почему в человеке заложена потребность шутить, почему люди, которые никогда не смеются, кажутся странными и неприветливыми? Моя теория такова, что мы все используем юмор как способ разрядить ситуацию (что имеет очевидное преимущество для выживания). Люди не побьют шутника – только если шутка старая или плохо рассказана. Если серьезно, то юмор сводит на нет трайбализм и эмоции, и позволяет людям работать вместе, даже если они сильно отличаются друг от друга. Общая шутка может создать сильные связи, потому что она свидетельствует о схожести взглядов. Юмор является неотъемлемой частью общества и уменьшает стресс.

*СОВЕТ:* Чем более серьезную тему затрагивает ваше сообщение, тем больше вам потребуется юмора. В моей книге о ZeroMQ мной написано много глупой чепухи вперемешку с тяжелым описанием технической части. Многим это понравилось. Если бы не алкоголь, то хмурое выражение лица индустриальной экономики никогда бы не сменялось улыбкой. Она себя очень серьезно воспринимает. Недостаток юмора в организации – явный признак того, что все там фундаментально убого. Хуже всего, что тогда группа становится уязвимой для конфликтов и расколов.

=== Минимализм

Гоночные машины делаются быстрее за счет избавления от лишнего веса, а не увеличения мощности. Вы можете сделать ваше сообщество более легким, быстрым и гибким, строго следуя догме минимализма по отношению к вашей работе. Это может смахивать на леность, но часто бывает сложнее не делать что-то веселое, чем ввязаться в это без оглядки.

Общее правило – делайте всегда тот минимум объема работ, которого будет достаточно, чтобы все работало. Остальное будете делать, когда люди начнут использовать вашу работу и жаловаться. Это относится как к вашему посевному проекту, так и к каждому изменению, которое вы вносите. Обратная связь – в большей степени, чем ваше собственное мнение, – лучший указатель того, где следует приложить усилия.

*СОВЕТ:* Перфекционизм препятствует участию. Публикация на половину оконченной и содержащей баги работы – прекрасный способ привлечь людей к участию. Для больших эго это трудно принять, но изъяны лучше привлекают участников, чем совершенный труд, который привлекает пользователей.

Культура минимализма может и должна распространиться в вашем сообществе. В прошлом мы обычно создавали юридические лица для серьезных проектов, чтобы была возможность владеть авторскими правами, торговыми марками и деньгами. Однако содержание юридических лиц дорого обходится и занимает много времени. Одна налоговая отчетность может стать непосильным бременем.

Одно из моих сообществ, http://www.digistan.org/[Digistan], было разработано, развито и достигло своего результата (формирование нового поколения узаконенных шаблонов и политических аргументов для открытых стандартов) где-то за шесть месяцев. Все наши протоколы в ZeroMQ основываются на работе Digistan. https://en.wikipedia.org/wiki/Open_Web_Foundation[Open Web Foundation], занимаясь теми же вопросами, потратило два года только на регистрацию юрлица, определение устава и выбор сотрудников.

=== Разумное финансирование

Если средств будет недостаточно, сообщество умрет от истощения. Если их будет слишком много, то, как я уже говорил, оно будет разлагаться. Здесь требуется чуткое равновесие. Мы можем мотивировать людей с помощью денег до определенной степени. После этого, только психопаты будут показывать пропорциональную реакцию. В этом и заключается дефект наивной теории капитализма о том, что «чем больше денег, тем лучше». В моем деле самыми вероломными оказывались те, кому я больше всего платил.

Первое, что нужно сделать для сокращения расходов, – это отказаться от идеи с юрлицами, офисами и сотрудниками, если только вы правда в них не нуждаетесь. Они не только съедят любые ваши средства, но они будут препятствовать вашей работе по созданию только онлайн-сообщества.

Второе: инвестируйте время и деньги в сообщество, только если нет другого выхода. Это может относиться к регистрации торговой марки, оплате хостинга или плате за выполнение такой работы, с которой больше никто не справится. И наконец: остерегайтесь людей, которые готовы взять на себе серьезные риски без требования соответствующего вознаграждения, – они склонны перегорать, о чем я расскажу в следующей главе.

*СОВЕТ:* Каждый раз, собираясь потратить деньги на сообщество, поинтересуйтесь, не может ли кто-нибудь вам помочь с проблемой.
