= Дополнительные аспекты

В предыдущей главе я представил свой инструментарий для создания онлайн-сообществ.
Теперь я рассмотрю несколько других ключевых идей, о которых стоит знать.

== Маркетинговая Кривая

https://www.google.com/search?q=marketing+curve[Маркетинговая кривая] - это хорошо известная теория в маркетинге, о которой мало знают в инженерии и создании сообществ. Однако важно понимать, как сообщества развиваются с течением времени. В классической маркетинговой кривой новая технология, идея или продукт входят на рынок как волна, начиная с энтузиастов и первопроходцев, затем ранних последователей, затем массового рынка, затем поздних последователей и, наконец, скептиков.

У каждой из этих групп есть разные мотивы для прихода в проект, присоединения к нему и, в конечном счете, ухода.
Если мы возьмем такую захватывающую новую технологию, как ZeroMQ, мы сможем исследовать ее и понять, как она работает:

* Когда проект молодой и экспериментальный, он привлекает экспертов и исследователей, которые ищут просто чего-то нового. Эти люди должны знать, почему проект отличается от того, что существует, каковы его цели и почему он интересен. Они никогда не будут этим пользоваться и не станут участниками. Они — ваши евангелисты. Часто они быстро теряют интерес.

* Когда у вас есть первая версия продукта, он привлекает ранних последователей. Это закоренелые хакеры, которые хотят знать всё самое новое и не заботятся о документации, маркетинге или обучающих программах. Они хорошо справляются с чем-то новым. Это ваша первая волна участников. Часто они создают фреймворки для других разработчиков.

* Когда у вас есть реальный, полезный продукт, он привлекает ранних последователей. Это люди, которые делают реальные продукты, но при этом хорошо умеют брать на себя риск и управлять им. Им по-прежнему не нужна большая помощь, хотя они и ожидают какой-то гарантии, что вещи не сломаются случайно. Это основная часть вашего сообщества.

* Когда вы выпустите вторую и третью версии продукта, вы начнете привлекать массовый рынок. Это люди, которые ожидают стабильности и надежности. Они будут задавать вопросы типа: "Вы предлагаете поддержку?" Некоторые из них станут участниками. Однако в основном они являются целевыми платежеспособными клиентами.

* Наконец, когда вы находитесь в более поздних версиях, отстающие и скептики, наконец, возьмут старые версии и попробуют их.

Конечно, всё может быть гораздо сложнее, потому у вас может быть несколько перекрывающихся кривых. Вам нужно заинтересовать весь рынок, иначе вы потеряете значимые части своего сообщества. Каждый этап порождает следующий, поэтому вы должны нацелить новые версии на энтузиастов, чтобы они могли продать их ранним последователям и так далее.

Как только вы поймете маркетинговую кривую, вы поймете, почему контрпродуктивно, например, писать идеальные учебники для ранних версий.
Вы все равно не получите массовый рынок, и это будет выглядеть слишком покровительственно по отношению к ранним последователям.

== Эмоциональное выгорание волонтеров

Ранее я подчеркивал ценность добровольной работы как более аккуратной, честной и творческой по сравнению с оплачиваемой работой. Однако здесь нужно сделать важную оговорку. Некоторые инструменты Социальной Архитектуры таят в себе опасность. Поставив людям захватывающую цель, вы можете подтолкнуть их в сторону саморазрушения. Это было главной проблемой в https://ffii.org/[FFII] (Foundation for a Free Information Infrastructure), когда я пришел туда, и ее усугублял высокий накал эмоций, характерный для родоплеменной корпоративной культуры организации в то время. Многие ключевые участники были изнурены и эмоционально истощены. Не понаслышке знакомое мне самому состояние.

Исследования эмоционального выгорания, о которых вы можете https://en.wikipedia.org/wiki/Occupational_burnout[прочитать в Википедии], на мой взгляд, не соответствуют тому, что происходит в реальной жизни. А реальность всё-таки важнее теории. Я неоднократно наблюдал такую характерную особенность выгорания в добровольных сообществах:

* Оно выражается как глубокое отвращение к конкретному проекту. Мы забрасываем проект подальше, прекращаем отвечать на эл. почту и можем даже покинуть сообщество. Остальные отмечают: «хм, он ведет себя как-то странно… наверно, расстроен или устал».
* Это состояние проекто-ёориентированно. Т.е. мы выгораем по отношению к одним проектам, а с другими все может быть нормально. В иных случаях нас может парализовать даже на несколько месяцев — потом мы опять начнем работать, но уже забросив проект и взявшись за что-то другое.
* Такое случается раз в один-три года, в зависимости от вашего характера и ситуации. Очень упорные, мотивированные личности могут выдержать дольше, но когда сорвутся, будет еще хуже.
* Лечение есть. Это наистраннейший подход я опробовал, когда удалось найти денег и заплатить перегоревшим добровольцам за то, что они делали бесплатно. Они вернулись счастливыми и продолжили заниматься своим делом.
* Недуг также можно предотвратить. Оплачиваемые работники не страдают также от истощения. Конечно, и они могут впасть в депрессию, но обычно их не вырубает внезапно.

Что приводит меня к мысли о том, что дело тут в проблеме оптимального вложения профессиональных усилий.

Люди много вкладывают в свои профессии, идут на большой риск, особенно в молодости в надежде на награду потом. Мы долгое время можем не придавать значения материальному вознаграждению, если мы уверены в том, что следуем верным путем. Например, молодой писатель или музыкант готов терпеть бедность многие годы, если он считает, что слава и богатство ждут его впереди.

И не важно, насколько пожухшая морковка свисает перед нами с палки — она всегда маячит у нас в подсознании. Мы по своей сути экономические животные. Вся жизнь — бухгалтерия. Мы превосходно умеем врать себе, но все же за каждым действием и решением стоит экономический мотив. Мы инвестируем в проекты, потому что чувствуем, что они будут способствовать нашему успеху, даже если на это уйдут годы. Мы соревнуемся с другими, пытаясь найти ниши, где наши таланты засияют во всей красе.

И вот получается так, что молодой мозг, изо всех сил старающийся инвестировать свои ресурсы в правильные вещи, обнаруживает себя в ситуации, когда снежный ком лжи достигает критической массы. Дорога внезапно заканчивается тупиком. Люди, которые ей следовали, — обманщики и манипуляторы. Миссия — фальшивка. Одобрения со стороны других — эмоциональное манипулирование. Годы усилий идут прахом, и каждая следующая минута становится бессмысленной жертвой.

Подобное выгорание похоже на расплату (like a reckoning). Мы бросаем проект так, будто он вдруг стал ядовитым, словно поняли, что проглотили какой-то протухший кусок. Вот несколько способов снизить вероятность подобного развития событий:

* Мы не можем в одиночестве работать над проектами. Концентрация всей ответственности на одном человеке, который не работает сверх меры, часто приводит к перегоранию.

* Проектам требуется бизнес-план. Надежда получить материальное вознаграждение позволяет мозгу мириться некоторое время с отсутствием вознаграждения.

* Превентивной мерой против выгорания может быть информация. Когда мы объясняем людям, что такое выгорание, они быстрее его распознают и просят о помощи еще до того, как дело заходит слишком далеко.

* Хорошие инструменты и практики позволяют нам работать с меньшим стрессом и с меньшей зависимостью от одного человека.

== Миф об индивидуальном интеллекте

Наверно, вы уже поняли, что я не сторонник одинокой гениальности.
По большому счету это объясняется тем, что, несмотря на членство в организации https://ru.wikipedia.org/wiki/Менса[Менса] (крупнейшая, старейшая и самая известная организация для людей с высоким IQ), я помню, как совершал на удивление гениальные ошибки.
Со временем я стал думать, что любое упоминание об индивидуальном интеллекте является опасно упрощенным мифом.

В нем всегда гениальные личности думают над важными проблемами, и в результате упорного труда они генерируют решения и шлифуют их до совершенства.
Иногда они переживают «эврика-моменты», когда им открываются гениально простые ответы на сложные проблемы.
Изобретатель, его процесс изобретения, исключительное, драгоценное явление, и остальным лучше не вмешиваться.
История полна героями-одиночками.
Мы обязаны им нашим современным миром.

Однако если присмотреться внимательнее, то станет понятно, что эта сказка не соответствует фактам.
История не показывает одиноких изобретателей.
Она рассказывает нам о везении людей, которые украли или присвоили себе право собственности на идеи, над которыми работали многие.
Она полна примеров про гениальных людей, которые после удачного попадания тратят десятилетия на бесполезные и безрезультативные поиски.
Самые известные крупные изобретатели вроде Томаса Эдисона были хороши в систематическом поиске, который выполнялся крупными командами.
Это как заявить, что Стив Джобс изобрел каждую примочку, сделанную командой «Apple».
Этот приятный миф годится для маркетинга, но он далек от истины.

История последних десятилетий, которая лучше зафиксирована и которой сложнее манипулировать, наглядно это демонстрирует.
Интернет точно является одной из самых инновационных и быстро развивающихся технологий, о становлении которой имеется большое количество достоверной информации.
У этой технологии нет изобретателя.
Вместо этого есть огромная масса людей, которые тщательно и успешно решали длинную серию текущих проблем, записывали свои ответы и делали их доступными для всех.

Инновационная природа Интернета обеспечена не маленькой избранной группой Эйнштейнов.
Она обеспечена RFC-документами, которые могут быть кем угодно использованы и улучшены, сотнями и тысячами умных, хотя и не уникально умных, людей, программным обеспечением с открытым кодом, который любой может использовать и улучшать.
Она происходит из обмена, смешивания и масштабирования сообщества.
Она происходит из постоянного увеличения числа хороших решений и избавления от плохих.

Хотя, вот и альтернативная теория инноваций:

. Есть безграничная область проблем/решений.
Словно область равнин и холмов, которые мы пытаемся преодолеть.
Решения интересных проблем находятся на вершинах холмов.
. Область меняется с течением времени в зависимости от внешних обстоятельств.
Горы могут превратиться в равнины, а новые горы могут возникнуть там, где их не было, со временем.
. Мы можем точно воспринимать только те проблемы, которые ближе к нам.
У нас нет возможности охватить взглядом все и нам остается полагаться на наши догадки.
Наш метафорический ландшафт очень туманен.
. Мы можем прикинуть, что нам даст и во сколько обойдется задача, оценивая решения. Т.е. мы можем понять, насколько высоко мы находимся.
. Есть оптимальное решение для любой решаемой проблемы.
Так, у любого склона есть вершина.
. Мы можем достичь это оптимального решения механически, шагнув в примерно правильном направлении и посмотрев, оказались ли мы выше, либо ниже.
. Наш интеллект может ускорить этот процесс, но не заменить его.
Если мы умнее — возможно мы будем шагать быстрее или чуть дальше видеть сквозь туман, и все.

Есть несколько последствий этого:

* Индивидуальная креативность значит меньше, чем сам процесс.
Более умные люди могут работать быстрее, но они могут и следовать в неправильном направлении.
Быть честными и объективными нам помогает коллективное видение реальности.
* Нам не нужны дорожные карты, если у нас хорошо налажен процесс.
Со временем, по мере того, как ценность решений будет расти, будет расти и функциональность.
* Мы не столько изобретаем решения, сколько открываем их.
Соболезнования творческим натурам: это всего лишь обрабатывающий информацию голем, начищающий свое собственное эго и озабоченный поднятием кармы.
* Интеллект — это социальный эффект, хотя он и ощущается как что-то личное.
Человек, отрезанный от других, перестает думать.
Мы не можем ни определить проблемы, ни оценить их решения без других людей.
* Размер и разнообразие сообщества является ключевым фактором.
Более крупные и разнообразные сообщества охватывают больше релевантных задач, решают их более точно и делают это быстрее маленькой группы экспертов.

Поэтому когда мы доверяемся экспертам-одиночкам, они делают классические ошибки.
Они фокусируются на идеях, а не на проблемах.
Они фокусируются на неправильных проблемах.
Они делают неправильные выводы о ценности решаемых проблем.
И они не пользуются тем, над чем работают.

== Коллективный Индекс Интеллекта или КИИ (CII)

Я собираюсь предложить инструмент по измерению интеллекта сообщества, другими словами, как точно и эффективно сообщество работает в любой взятый период времени.
Он также показывает, насколько приятно будет участвовать в сообществе.

Для его демонстрации я ранжирую несколько сетей, организаций, сайтов и онлайн-сообществ.
Это не наука, просто творческая и небрежная прикидка.
Как всем известно, 87% статистики изобретается на месте, и 91% людей принимают это без вопросов.
Я выбрал следующие жертвы:

. Википедия
. Твиттер
. Реддит
. Фейсбук
. Индустрия моды
. Нигерийский кинематограф, т.н. Нолливуд (Nollywood)
. Адвокаты как профессия
. Киноиндустрия Голливуда
. Сеть The Fox News
. Военные (в какой-то случайной восточной стране)

Я не буду судить о ценности отдельно взятого сообщества.
Это невозможно, и будет обманчиво.
Миссия Твиттера — «набрать больше подписчиков» — звучит слабее, чем у Википедии «собираем знания всего мира».
Однажды сформированная, умная и гибкая толпа может запросто создавать новые миссии, например «свергнуть диктатора».
Онлайн-сообщество, возможно, ценно (для человечества) не благодаря своей продукции, а само по себе.
В случае Википедии или ZeroMQ сложно отделить толпу от контента.
А в случае Твиттера это очевидно.
Контент — явление преходящее и зачастую бесполезное, а толпа — нет.

Я придумал такую оценочную таблицу:

[cols="<,<,<,<,<,<"]
|===
|Критерий |1.Wk |2.Tw |3.Rd |4.Fb |5.Fa

|Четкая миссия |5 |3 |2 |1 |2
|Свободное участие |5 |5 |5 |5 |4
|Прозрачность |5 |3 |5 |1 |2
|Бесплатные участники |5 |5 |5 |5 |2
|Ремиксабельность |5 |5 |5 |4 |4
|Четкость протокола |5 |5 |5 |4 |4
|Компетентность власти |5 |4 |5 |3 |4
|Нон-трайбализм |4 |5 |5 |5 |3
|Самоорганизация |5 |5 |5 |5 |4
|Толерантность |5 |5 |5 |5 |4
|Измеримый успех |5 |5 |5 |5 |5
|Высокое награждение |3 |5 |5 |5 |4
|Децентрализация |5 |5 |5 |5 |5
|Свободная рабочая среда |5 |5 |5 |5 |3
|Стандартная структура |4 |5 |5 |5 |3
|Плавность обучения |5 |5 |5 |4 |3
|Позитивность |5 |5 |5 |5 |5
|Чувство юмора |5 |5 |5 |5 |2
|Минимализм |5 |5 |4 |4 |3
|Разумное финансирование |5 |4 |3 |3 |5
|*Итоговый счет* |*96* |*94* |*94* |*84* |*71*
|===

[cols="<,<,<,<,<,<"]
|===
|Критерий |6.Nw |7.Lw |8.Hw |9.FN |10.Ml

|Четкая миссия |1 |0 |0 |0 |2
|Свободное участие |3 |0 |1 |2 |2
|Прозрачность |1 |0 |0 |0 |0
|Бесплатные участники |3 |3 |2 |1 |0
|Ремиксабельность |3 |3 |1 |1 |0
|Четкость протокола |3 |2 |3 |1 |4
|Компетентность власти |3 |1 |1 |0 |1
|Нон-трайбализм |3 |0 |2 |0 |0
|Самоорганизация |4 |2 |2 |0 |0
|Толерантность |3 |2 |3 |0 |0
|Измеримый успех |5 |4 |5 |5 |2
|Высокое награждение |3 |3 |2 |1 |1
|Децентрализация |1 |1 |1 |0 |1
|Свободная рабочая среда |2 |0 |0 |0 |0
|Стандартная структура |3 |0 |1 |0 |0
|Плавность обучения |2 |3 |3 |1 |5
|Позитивность |3 |0 |2 |0 |0
|Чувство юмора |3 |0 |1 |1 |0
|Минимализм |4 |1 |1 |3 |0
|Разумное финансирование |3 |3 |3 |2 |2
|*Итоговый счет* |*56* |*28* |*34* |*18* |*20*
|===

Если мы можем измерить КИИ сообщества или организации, значит, мы можем улучшить его, уделив внимание аспектам с низкими оценками.
В теории это должно сделать организацию умнее, а ее участников счастливее.
Конечно, довольно характерно, что военная организация может работать только с низким КИИ. Умная армия, скорее всего, просто разойдется по домам и переключится на Reddit.

== Как захватить/защитить open-source проект

На «Ars Technica» http://arstechnica.com/gadgets/2013/10/googles-iron-grip-on-android-controlling-open-source-by-any-means-necessary/[есть интересная статья] о том, как Google понемногу закрывает Android. Это классическая игра Capture the Flag, которая ведется против open-source сообщества. Я собираюсь объяснить, как этот захват работает, и как его предотвратить.

=== Почему Capture the Flag?

Как говорит «Ars Technica»: «Легко отдать что-нибудь, когда ты на последнем месте с нулевой долей рынка, как это было с Android в начале. Когда же ты на первом месте, немного сложнее быть таким открытым и доброжелательным».

Android, если уж честно, вероятно, самая крупная инвестиция Google. Вы можете поспорить о том, имеют ли они право превращать открытую систему в закрытую, и вы будете правы. Однако это то же самое, что спорить о том, имеет ли право центральный банк печатать слишком много денежных знаков и создавать девальвацию. Конечно, на это он уполномочен. Но в то же время у этого существует цена, которую заплатят другие люди. Вопрос не в правомерности, а в приемлемости той цены, которую заплатит общество. А если она неприемлема, тогда как это предотвратить?

Android, как и любая система с открытым кодом, проданная рынку на этой основе, является общественной собственностью. Когда кто-либо приватизирует ее, он увеличивает свои прибыли, как печатающий деньги центральный банк, за счет остальных. Делая форк таких приложений Android, как поиск, календарь, музыка, и создавая улучшенные их версии, Google соперничает с другими компаниями, использующими Android на своих устройствах.

Вопрос о захвате, о том, как это происходит и как это предотвратить, особенно важен, если вы не Google, т.е. если вы пользователь или участник open-source-проекта. В Android много патчей других фирм, таких как LG, Samsung и прочие. По мере того как Google превращает операционную систему в свой личный огород, эти патчи начинают использоваться против тех же самых людей, которые их сделали.

Я уверен, что Google совершает огромную ошибку, меняя правила игры подобным образом, просто потому что это будет потворствовать конкурентам Android. Однако я не об этом. Я просто заинтересован в усвоении любых уроков, которые помогут мне с моей работой и моими проектами.

Отмечу две вещи:

* из чистого интереса я не буду участвовать в open-source-проекте, который не предоставит мне, участнику, гарантий того, что мои патчи и изменения не станут принадлежать кому-либо еще и не будут использоваться против меня же.
* из соображений этики я никогда не создам open-source-проект, который не будет обеспечивать подобные гарантии своим участникам.

=== Сценарий использования

Я постараюсь выразиться недвусмысленно о сценарии использования. Речь идет об Android: одна компания начинает open-source-проект, используя его как «товар-приманку», намереваясь проникнуть на рынок, и просит поддержки у других. Это классическая стратегия, которая может быть очень успешной. Однако это точно не то же, что студенческий проект-исследование или мусор вроде «давайте сделаем систему расчетов по заработной плате open-source» или «пятеро из нас собрались в гараже и решили сделать новый фреймворк».

Здесь есть частичное совпадение, и я думаю, полученные выводы можно применять более широко (и я точно применяю их систематически), опять же, мой сценарий использования – «open-source для прорыва на рынок».

Важно знать, что успех использования open-source-проекта для прорыва на рынок зависит от сообщества, которое за него берется. Любой рынок зависит от поведения нескольких влиятельных игроков, доминирующих на рынке, а усилия большинства остальных игроков несущественны. Суть в том, чтобы обещать этой удрученной бессилием толпе выход, убедить их инвестировать во что-то новое и открытое, которое потенциально может изменить правила игры.

Большинство open-source проектов провальные (серьезно, идите, почитайте о каком-нибудь случайном проекте на GitHub и увидите, сколько из них адекватных), и даже успешные в очень скромном значении этого слова, незначительны сами по себе. Пока нет серьезного изменения власти, проект может оставаться потенциальным прорывом на рынке очень долгое время. Он может выглядеть очень стабильным и счастливым. Что ж, легко быть дружелюбным, когда на кону не стоят деньги.

Если и когда проект становится успешным, правила игры меняются, умные парни, которые запустили прорывной проект, стараются сорвать спелый фрукт и забрать его себе. И вот только тогда становится интересно.

=== Поле с равными условиями игры не под «запретом»

Есть несколько способов захватить open-source проект, включая товарные знаки и патенты. Я рассмотрю только авторские права, потому что это наиболее частый случай. Ключевыми соглашениями, которыми регулируются авторские права на open-source проект, являются а) лицензия и б) политика участия.

Частым заблуждением является мысль о том, что open-source проект не может быть захвачен. Это совершенно не верно. Грубо говоря, есть три типа соглашений об авторских правах:

. «закрытая» лицензия, которая не позволяет повторно обрабатывать материал, классическое авторское право плюс некоторые ограничительные лицензии;
. лицензия «free to take», которая позволяет одностороннюю обработку материала, например Apache/BSD/MIT;
. лицензия «share-alike», которая позволяет двустороннюю обработку материала, например GPL, LGPL и cc-by-sa.

Представьте себе ди-джея, который выпускает популярный бит по модели «free to take». Ведущий музыкальный лейбл делает из бита ремикс и выпускает его. Тот становится хитом. И теперь эта новая версия закрыта. Ди-джей не может ремиксить эту новую работу, и, возможно, не может даже проигрывать ремикс. Конечно, он может взять свою старую версию и улучшить ее, однако деньги будет приносить коммерческая версия.

Надеюсь, вы понимаете, к чему я клоню. Даже лучший индивидуальный талант не сможет конкурировать на равных с крупной фирмой с ее маркетинговым и денежным ресурсами. Единственный способ гарантировать равные условия игры в войне за контроль над развитием — *двухсторонняя гарантия ремиксабельности*. Двусторонняя — значит касается обеих сторон.

Когда люди называют эту гарантию "ограничительной", остается только вздыхать по этому поводу. Это как называть замок в моей машине "ограничением", потому что он останавливает остальных от присвоения моей машины. Назвать защиту от воров "ограничением" это... ну, по меньшей мере, неумение анализировать. Когда правила работают для обеих сторон, это не ограничение, ОК?!

=== Как происходит захват?

Давайте еще раз определимся с целью. Необходимо предотвратить захват open-source проекта кем-то с большими деньгами и властью, кто нацелился собрать урожай с проекта для своей личной выгоды, за счет сообщества, которое помогало развивать или создало проект. Мне все равно, насколько «правомерен» будет этот захват, я просто объясняю, как его предотвратить.

Лицензия и политика участия являются двумя половинками одной головоломки.

Кто владеет авторскими правами? Они «сконцентрированы» у основателей проекта или они разделены между всеми участниками? Это жизненно важный вопрос. Если они сконцентрированы, то это тривиальная задача по покупке авторских прав, разветвлению проекта, изменению лицензии в одностороннем порядке, — и можно двигаться в закрытом направлении. Однако если права распределены, т.е. многие люди владеют работой, совместно владеют, то вам нужно одобрение всех (не большинства, а 100% единодушие) для изменения лицензии. А это логистически невозможно.

Кстати, если бы вы только знали, сколько людей мне предлагали деньги за коммерческую лицензию на ZeroMQ, вы были бы поражены (очень много). Предложение простое: я продаю им лицензию «non-LGPL», они платят мне хорошие деньги и делают свои версии ZeroMQ. Если бы я специально не позаботился о невозможности этого варианта давным-давно, то я бы был очень богатым. И теперь мириться с бедностью мне помогает осознание того, что ZeroMQ переживет меня.

Давайте еще раз пройдемся по проблеме с предложением коммерческих лицензий для совместной работы. Представьте себе клуб, который приглашает ди-джеев и микширует их биты. Потом клуб оставляет за собой авторские права и продает их звукозаписывающей компании, которая делает свой альбом ремиксов, которые первоначальные ди-джеи уже не могут проигрывать бесплатно. Поэтому да, я считаю двойное лицензирование GPL/коммерческая лицензия порочной практикой.

Никто не будет платить за коммерческую лицензию проекта «free to take», потому что они могут просто взять код и использовать его. В некоем смысле я считаю, что это уже неправильно, т.к. нарушает равенство правил игры для всех. Ведь очевидно, что крупная компания выиграет от этого больше, чем маленькие команды. Опять же представьте себе независимого ди-джея, противостоящего звукозаписывающим лейблам со всеми их маркетинговыми и медийными связями и доходами от концертов.

Теперь перейдем к шагу по захвату номер два: найм разработчиков.

«Но код все еще свободен!», — говорят люди. Конечно. Возвращаемся к лейбл vs ди-джей. Пусть лейбл нанимает только одного ди-джея, ключевого сотрудника и использует его, чтобы протолкнуть коммерческий микс альбома. Куда публика тогда пойдет?

Вам не нужно нанимать всех участников в сообществе, чтобы захватить его. В любом случайно взятом проекте будет два-три топовых участника и огромная масса младших. Наймите двух топов и вы можете забрать проект куда угодно. Если результаты могут повторно обрабатываться (ремиксабельны), то это путешествие будет полностью справедливо по отношению к тем, кто участвовал в проекте раньше. А если не ремиксабельно, то все остальные участники обнаружат, что их инвестиции используются против них.

=== Предотвращая захват

Я знаю только одну модель, которая предотвращает захват open-source проекта в области ПО:

. Лицензия семейства «GPL» (или MPLv2, которая работает схожим образом).
. Распределенные авторские права

Именно так я строю open-source проекты с самого начала, и это требование к любому сообществу, к которому я присоединяюсь. Ваше право делать деньги не включает мое право использовать мою работу как конкурентное преимущество, если только это не взаимовыгодно.

== Юридический справочник: Товарные знаки

Товарные знаки.
Что это такое, нужны ли они вам и сколько они стоят?
Это вопросы, которые часто возникают, когда мы создаем проекты с открытым исходным кодом.
Товарные знаки могут быть ключом к защите проекта от злоумышленников.
Тем не менее, в интернете мало советов.
Итак, вот мое руководство по использованию товарных знаков в открытом исходном коде.
Это практический совет, я не адвокат, и уж точно не ваш адвокат.

=== Предыстория товарных знаков

(_прим. перев._: рассматривается законодательсто США)

Сначала определения.
Товарный знак — это название, фраза, логотип или даже определенный цвет ("знак", "марка"), который вы используете для бизнеса ("товара", "торговли").
Простой факт использования знака в течение некоторого периода времени утверждает товарный знак.
Однако, как и в случае со всякой собственностью, дьявол кроется в правоприменении.
Всегда возникает вопрос, если вы пойдете к судье с жалобой, какие стандарты доказательств будет ожидать и требовать судья?

В любом случае, уголовном или гражданском, всё сводится к убеждению одного или нескольких человек.
Если вы когда-нибудь обратитесь в суд, имейте это в виду.
Факты дела в том виде, в каком они известны каждой стороне, не имеют значения.
Важно только то, как эти факты задокументированы и представлены.

Давайте вернемся немного назад и спросим, почему суды вообще заботятся о защите товарных знаков компаний.
Во-первых, это защита потребителей от вводящей в заблуждение тактики продаж.
Простая продажа хлама как таковая не является правонарушением, за исключением случаев, когда существуют законные минимальные стандарты охраны здоровья и безопасности.
Однако продажа хлама, который выдает себя за более дорогой, хорошо известный бренд, является правонарушением.
Итак, во-вторых, товарные знаки позволяют компаниям выделиться и остановить недобросовестную конкуренцию.

Поэтому судья по делу о нарушении прав на товарный знак спросит: "Было ли намерение обмануть потребителя?
Будет ли обманут разумный потребитель?" И тогда судья спросит: "Кому принадлежал товарный знак, и могут ли они это доказать?" Даже при том, что простое действие с использованием знака создает его (в соответствии с так называемым общим правом), это может быть трудно установить.

Например, компания А создает сеть ресторанов.
Компания Б открывает конкурирующую сеть, использующую те же цвета и похожее название.
Б явно присваивает инвестиции A в брендинг, присваивает репутацию.
Тем не менее, когда A подает на Б в суд, Б предъявляет документ, показывающий планы их ресторана, за целый год до того, как A начал.
Как судья узнает, кто лжец?

В очевидных случаях вы можете убедить судью в том, что подражатель обманывает потребителей и присваивает вашу репутацию.
Тем не менее, риск проигрыша такого дела очень высок.
Кроме того, рассмотрение таких дел обходится судам дорого.
Судьи могут просто отказаться их выслушивать.

Следовательно, большинство стран предоставляют возможность зарегистрировать ваши знаки за определенную плату.
Регистрация дает вам документ за конкретную дату, подтверждающий ваши права на товарный знак.
Ведомство по товарным знакам выполняет поиск предшествующих товарных знаков в той же области.
Прежде чем предоставить вам регистрацию, оно публикует вашу претензию и дает другим возможность оспорить ее.
Таким образом, после поиска и при отсутствии разногласий, судья примет регистрацию товарного знака в качестве веского доказательства.

Это не так просто.
Конкурент всё равно может заявить, что его знак общего права перевешивает ваш зарегистрированный товарный знак.
Они могут возразить, что регистрация не представляет реальной доброй воли.
Это часто понимается как "если вы не будете применять свой знак, вы его потеряете", что неверно.
Как владелец товарного знака, от вас не ожидают, что вы будете контролировать мир.
Однако от вас ожидают правдивости в суде, когда судья спросит вас: "Используете ли вы свой товарный знак и терпите ли реальный ущерб из-за недобросовестной конкуренции?"

Наконец, суды рассматривают товарные знаки для применения в каждом сегменте рынка.
Таким образом, вы можете иметь "XYZ Car Co" и "XYZ Clothing Co", не создавая путаницы на рынке.
Когда вы регистрируете знак, вам нужно будет объяснить, в каких "классах" вы ее используете.
Вы, вероятно, захотите международный класс 9, то есть всё, что подает звуковой сигнал.

=== Где и как зарегистрироваться

Если вы достаточно велики, чтобы нуждаться в регистрации в нескольких странах, то вы достаточно велики, чтобы иметь юристов по торговым маркам.
Для остальных из нас это немного похоже на покупку доменного имени.
Конечно, существуют сотни доменных расширений.
Тем не менее, мы по-прежнему хотим, чтобы доткомы были нашим основным бизнесом.

Так же обстоит дело и с товарными знаками.
Если вы решите зарегистрировать знак, сначала сделайте это в США (через USPTO).
Это дешево и просто.
Затем, со временем, вы сможете зарегистрироваться в ЕС (через OHIM), если сочтете, что ваш проект того стоит.

Стоимость регистрации в США составляет около 1500 долларов США, в зависимости от того, какого юриста вы используете.
Вы можете найти адвокатов по товарным знакам в Интернете.
Они попросят вас предоставить подробную информацию о знаке, доказательство того, что он используется, имя и адрес владельца регистрации, а также данные кредитной карты.
Этот процесс занимает около шести месяцев.
Через девять лет (и до истечения десяти лет) вы можете обновить товарный знак.

Получение регистрации в США ускорит регистрацию в других странах, если вы решите подать заявку на это позже.
Риск, и он невелик, заключается в том, что тролль зарегистрирует вашу торговую марку в какой-нибудь другой стране, фактически лишив вас возможности вести там бизнес под этим именем.

Однако, прежде чем зарегистрироваться, спросите себя: "Какова вероятность того, что кто-то украдет мое имя и логотип?" Если она низкая, не беспокойтесь.
Если она высока, то спросите: "Какова вероятность того, что мошенник обратится с этим в суд?" Если это все еще низкий показатель, то тоже не беспокойтесь.

Вместо регистрации знака вы можете повысить его заметность.
Это означает, что вы должны быть откровенны на своем веб-сайте и в других материалах.
"X, Y и Z являются товарными знаками MyCorp". Это отпугивает потенциальных мошенников, улучшает ваше дело, если вы все-таки попытаетесь защитить знак в суде, и облегчает получение регистрации, если и когда она вам понадобится.

=== Как защитить свой товарный знак

Независимо от того, зарегистрированы вы или нет, вы обеспечиваете соблюдение своего знака, сообщая другой стороне в письменной форме: "Остановись сейчас, иначе". Если они не останавливаются, вы повторяете предупреждение с первоначальными требованиями о возмещении ущерба.
Если они не остановятся, вы добавите еще больше убытков, и когда у вас будет солидное досье, вы подадите в суд.

Подавляющее большинство людей сразу же отступят.
Проблема возникает, когда вы сталкиваетесь с кем-то, кто хорошо знаком с законом о товарных знаках, располагает дешевыми юридическими ресурсами и любит проводить время в суде.

Если вы столкнулись с такой фирмой, и вы не зарегистрировали свой знак, вам, вероятно, следует сложить руки и сменить свое имя.
Велик риск того, что вы проиграете, и вам придется заплатить высокие судебные издержки и, возможно, ущерб.
Судьи не всегда понимают это правильно.

Если вы все-таки зарегистрировали свой знак, то вам следует настаивать и требовать возмещения убытков.
Вы выиграете, если будете придерживаться основных правил (вы все еще используете знак, ущерб реален.) Нужно ли мне говорить, что любое судебное разбирательство должно происходить в стране регистрации?
Судьи в Бельгии не будут принимать документы от USPTO.

=== Товарные знаки для проектов с открытым исходным кодом

Распространенное заблуждение об открытом исходном коде заключается в том, что, поскольку код бесплатный, он не представляет собой ни чьей-либо собственности, ни ценности.
Обратное верно: успешные проекты представляют значительную ценность, которой владеют многие.
Как товарный знак представляет и защищает эту ценность?

Всё сводится к подлинности и репутации.
Если вы загружаете пакет, называющий себя "XYZ v2.0", то у вас могут быть ожидания.
Он совместим; он работает; в нем нет троянов или рекламы; он от тех же людей, что и "XYZ v1.0".

Если успешный проект не регистрирует свое название, то любой желающий может скопировать его, переупаковать и использовать то же название.
Представьте себе конкурирующие, несовместимые версии "Linux".

Когда физическое или юридическое лицо регистрирует название в качестве товарного знака, эти несовместимые копии всё еще могут существовать.
Однако они могут не использовать этот знак.
Если они попытаются это сделать, то это их время.

У меня это случалось по крайней мере один раз в моих собственных проектах, и товарный знак был инструментом, который я использовал, чтобы остановить несовместимые копии и наказать виновных.
Закон о товарных знаках достаточно ясен, что фраза "нарушение товарного знака" остановит 99% мошенников на месте.
Получение регистрационного номера останавливает 99% остальных действий.

В таком серьезном проекте, как ZeroMQ, вы получите три или четыре товарных знака, которые хотите зарегистрировать, в течение пяти-десяти лет.
Регистрируйте только тогда, когда это того стоит.
То есть для защиты реальных товарных знаков, которые вы были бы готовы защищать в суде.
Учтите, что в худшем случае вам, возможно, придется потратить в десять или двадцать раз больше стоимости регистрации, чтобы защитить свой знак.
Возможно вы возместите ущерб, а может и нет.

Я надеюсь, что этот небольшой обзор помог вам понять товарные знаки и то, как их использовать (или не использовать) в ваших проектах с открытым исходным кодом.
И как защитить себя, если кто-то заявит, что вы нарушаете их товарный знак.
(Подсказка: попросите у них регистрационный номер.)