= Послесловие

Эта книга рассказывает длинную историю, которая началась, когда я прочитал размышления Столлмана о написании его первого свободного программного обеспечения. В 2005 году мы строили онлайновые сообщества сознательно и агрессивно в политических целях. Тогда мы систематизировали теорию и применяли ее снова и снова. В 2007 году я использовал эти знания для создания большого сообщества для платформы Wikidot.com, в которую я вложил капитал, и был генеральным директором. В 2009 году я использовал эти знания качестве основы для сообщества ZeroMQ, и к 2011 году полностью сжег старые неуклюжие паттерны и заменил их модернизированными современными техниками.

Мы все еще учимся, делая наши процессы более простыми, а наши инструменты лучше. C4 не для всех. Требуется мужество принимать неизвестных вкладчиков и доверять им по умолчанию. Требуется опыт, чтобы понять, что за одной из двадцати улыбок скрыт недоброжелатель. Эти уроки медленно учат нас. Даже с полным руководством вам понадобятся годы чтобы его понять. Поэтому практикуйтесь, будьте готовы часто терпеть неудачу и быть счастливыми. :)
